### ISSUE TITLE
Install Error Windows OS ninja-build

### ISSUE THREAD

**Issue by etree19** [ANTsX/ANTsPy#775]
I am attempting to install antspy using the command pip install antspyx in Visual Studio 2022 Developer Powershell. When building wheel for antspyx I receive the following errors:

-- CMake Error at CMakeLists.txt:105 (message):
        ITK source code directory path length is too long (107 > 50).Please move
        the ITK source code directory to a directory with a shorter path.

AND

      -- Configuring incomplete, errors occurred!
      ninja: error: loading 'build.ninja': The system cannot find the file specified.

I currently have both ITK and ninja installed at 'C:/ITK' and 'C:/ninja' respectively. I have also added the location 'C:/ninja' to the PATH environment variable and set the environment variable ITK_DIR to "C:/build/ITK".

Since I have added ninja to my PATH environment variable and installed ITK in the shortest possible directory, I am not positive why these errors occured.

**ANTsPy installation:**
 - Hardware [PC]

 - OS: [Windows]
 
 - System details [
 OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19045 N/A Build 19045
System Type:               x64-based PC]

 - Sub-system: [none]

 - ANTsPy version: [N/A install issue]

 - Installation type: [pip]

**Comment by cookpa** [comment]
Unless you've modified the code, pip will build ITK itself, and won't use your system ITK. It will build in an isolated environment, which could be at some long path depending on how your python environment is set up.

One workaround might be to edit `ANTsPy/Scripts/configure_itk.bat`. On the line that starts

`cmake -GNinja -DITK_USE_SYSTEM_PNG=OFF`

add

` -DITK_SKIP_PATH_LENGTH_CHECKS=ON`

**Comment by etree19** [comment]
Thank you for the suggestion. This may be a very beginner question, but if I am installing using pip, how/when do I edit the configuration script?

**Comment by etree19** [comment]
I think I managed to get further with those suggestions, but I am still having issues building. I now am receiving many command line warnings. As an example:

      cl : Command line warning D9025 : overriding '/arch:SSE' with '/arch:SSE2'
      [2023/2241] Building C object Modules\ThirdParty\MINC\src\libminc\CMakeFiles\itkminc2.dir\volume_io\Prog_utils\arrays.c.obj

and the final error of:

      C:\Users\myusr\source\repos\antspy\build\cp313-cp313-win_amd64\Release\lib.cp313-win_amd64.pyd : fatal error LNK1120: 163 unresolved externals [C:\Users\myusr\source\repos\antspy\build\cp313-cp313-win_amd64\lib.vcxproj]

      *** CMake build failed

which was preceded by many, more specific, linking errors. For example:

       nanobind-static.lib(error.obj) : error LNK2001: unresolved external symbol __imp__PyGILState_Release [C:\Users\myusr\source\repos\antspy\build\cp313-cp313-win_amd64\lib.vcxproj]
      nanobind-static.lib(nb_ndarray.obj) : error LNK2019: unresolved external symbol __imp__PyObject_CallMethod referenced in function "struct nanobind::detail::ndarray_handle * __cdecl nanobind::detail::ndarray_import(struct _object *,struct nanobind::detail::ndarray_config const *,bool,struct nanobind::detail::cleanup_list *)" (?ndarray_import@detail@nanobind@@YAPAUndarray_handle@12@PAU_object@@PBUndarray_config@12@_NPAUcleanup_list@12@@Z) [C:\Users\myusr\source\repos\antspy\build\cp313-cp313-win_amd64\lib.vcxproj]
      nanobind-static.lib(nb_ndarray.obj) : error LNK2019: unresolved external symbol __imp__PyCapsule_Type referenced in function "struct nanobind::detail::ndarray_handle * __cdecl nanobind::detail::ndarray_import(struct _object *,struct nanobind::detail::ndarray_config const *,bool,struct nanobind::detail::cleanup_list *)" (?ndarray_import@detail@nanobind@@YAPAUndarray_handle@12@PAU_object@@PBUndarray_config@12@_NPAUcleanup_list@12@@Z) [C:\Users\myusr\source\repos\antspy\build\cp313-cp313-win_amd64\lib.vcxproj]
      nanobind-static.lib(error.obj) : error LNK2019: unresolved external symbol __imp__PyException_SetCause referenced in function "void __cdecl nanobind::chain_error(class nanobind::handle,char const *,...)" (?chain_error@nanobind@@YAXVhandle@1@PBDZZ) [C:\Users\myusr\source\repos\antspy\build\cp313-cp313-win_amd64\lib.vcxproj]
      nanobind-static.lib(error.obj) : error LNK2019: unresolved external symbol __imp__PyException_SetContext referenced in function "void __cdecl nanobind::chain_error(class nanobind::handle,char const *,...)" (?chain_error@nanobind@@YAXVhandle@1@PBDZZ) [C:\Users\myusr\source\repos\antspy\build\cp313-cp313-win_amd64\lib.vcxproj]
      nanobind-static.lib(error.obj) : error LNK2019: unresolved external symbol __imp__PyErr_FormatV referenced in function "void __cdecl nanobind::chain_error(class nanobind::handle,char const *,...)" (?chain_error@nanobind@@YAXVhandle@1@PBDZZ) [C:\Users\myusr\source\repos\antspy\build\cp313-cp313-win_amd64\lib.vcxproj]
      nanobind-static.lib(error.obj) : error LNK2019: unresolved external symbol __imp__PyErr_NewException referenced in function "struct _object * __cdecl nanobind::detail::exception_new(struct _object *,char const *,struct _object *)" (?exception_new@detail@nanobind@@YAPAU_object@@PAU3@PBD0@Z) [C:\Users\myusr\source\repos\antspy\build\cp313-cp313-win_amd64\lib.vcxproj]
      nanobind-static.lib(error.obj) : error LNK2019: unresolved external symbol __imp__PyFrame_GetLineNumber referenced in function "public: virtual char const * __thiscall nanobind::python_error::what(void)const " (?what@python_error@nanobind@@UBEPBDXZ) [C:\Users\myusr\source\repos\antspy\build\cp313-cp313-win_amd64\lib.vcxproj]
      nanobind-static.lib(error.obj) : error LNK2019: unresolved external symbol __imp__PyFrame_GetCode referenced in function "public: virtual char const * __thiscall nanobind::python_error::what(void)const " (?what@python_error@nanobind@@UBEPBDXZ) [C:\Users\myusr\source\repos\antspy\build\cp313-cp313-win_amd64\lib.vcxproj]
      nanobind-static.lib(error.obj) : error LNK2019: unresolved external symbol __imp__PyFrame_GetBack referenced in function "public: virtual char const * __thiscall nanobind::python_error::what(void)const " (?what@python_error@nanobind@@UBEPBDXZ) [C:\Users\myusr\source\repos\antspy\build\cp313-cp313-win_amd64\lib.vcxproj]
      C:\Users\myusr\AppData\Local\Programs\Python\Python313\libs\python313.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86' [C:\Users\myusr\source\repos\antspy\build\cp313-cp313-win_amd64\lib.vcxproj]
      C:\Users\myusr\source\repos\antspy\build\cp313-cp313-win_amd64\Release\lib.cp313-win_amd64.pyd : fatal error LNK1120: 163 unresolved externals [C:\Users\myusr\source\repos\antspy\build\cp313-cp313-win_amd64\lib.vcxproj]

**Comment by cookpa** [comment]
I don't know if ANTsPy builds on Python 3.13. 

If you can install Python 3.12, you might be able to install the binaries from pip, and avoid compilation from source.

**Comment by etree19** [comment]
Thank you for letting me know! The solution turned out to be: completely uninstalling python and any ANTsPy remnants, installing Python 3.12, using the Microsoft Visual Studio Developer Powershell, and installing the binaries from pip using the command "pip install antspyx".

Thank you again for your time! Marking as closed.
